# Generated by Django 4.0.2 on 2023-04-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
